config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  root  'static_pages#home'
  
  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'contact' => 'static_pages#contact'

  resources :users do
    get 'history' => 'book_states#index'
    resources :requests
    resources :favorites
  end

  match '/users/:id/:type', to: 'users#show', via: :get
  resources :relationships, only: [:create, :destroy]

  resources :categories do
    resources :books
  end
  resources :books do
    resources :reviews
    resources :book_states
  end
  resources :reviews do
    resources :comments
  end
  resources :activities do
    resources :likes, only: [:create, :destroy]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :requests
    resources :books
  end

  resources :activities
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :book_states, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :publish_date, presence: true
  validates :author, presence: true, length: {maximum: 150}
  validates :number_of_pages, presence: true
  validates :category, presence: true

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true

  mount_uploader :image, PictureUploader

  def self.search(search, filter, category)
    if search
      if category.blank?
        where("#{filter} LIKE ?", "%#{search}%")
      else
        where("category_id = ? AND #{filter} LIKE ?", "#{category}", "%#{search}%")
      end
    else
      all
    end
  end

  def state user
    book_state = BookState.find_by book: self, user: user
    book_state.nil? ? "unread" : book_state.state
  end

  def average_rating
    self.reviews.average :rating
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  helper_method :sort_column, :sort_direction
  respond_to :html, :js

  def index
    @books = Book.search params[:search], params[:filter], params[:category_id]
    @books = @books.order sort_column + ' ' + sort_direction
    @books = @books.paginate page: params[:page], per_page: 20
  end

  def new
    @book = Book.new
    @photo = @book.photos.build
  end

  def edit
    @book = Book.find params[:id]
  end

  def create
    @book = Book.new book_params
    
    if @book.save
      flash[:success] = "Book created!"
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def update
    @book = Book.find params[:id]
    if @book.update_attributes book_params
      flash[:success] = "Book updated!"
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find params[:id]
    Activity.destroy_all(target_id: @book.id, 
        action_type: ["read", "reading", "unread", "favorite", "unfavorite"])
    @book.destroy
  end

  private
  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def book_params
    params.require(:book).permit :title, :image, :author, :number_of_pages, :publish_date, 
                          :category_id, photos_attributes: [:id, :image, :_destroy]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :authenticate_user!, only: :show

  def index
    @books = Book.search params[:search], params[:filter], params[:category_id]
    @books = @books.order sort_column + ' ' + sort_direction
    @books = @books.paginate page: params[:page], per_page: 10
  end

  def show
    @book = Book.find params[:id]
    @book_state = BookState.find_by book: @book, user: current_user
    @reviews = @book.reviews.paginate page: params[:page], per_page: 10
  end

  private
  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def book_params
    params.require(:book).permit :title, :author
  end
end

app/helpers/book_helper.rb
module BookHelper
  def new_or_edit_book_book_state_path book, book_state
    book_state.nil? ? new_book_book_state_path(book, book_state) :
                      edit_book_book_state_path(book, book_state)
  end
end

app/views/admin/books/_book.html.erb
<tr id="book_<%= book.id %>">
  <td>
    <%= image_tag "#{book.image}", size: "32x32", alt: "Book", class: "img-rounded" %>
  </td>
  <td><%= link_to book.title, edit_admin_book_path(book) %></td>
  <td><%= book.author %></td>
  <td><%= book.average_rating.round 2 if book.reviews.any? %></td>
  <td>
    <%= link_to "edit", edit_admin_book_path(book), class: "btn btn-success" %>
    <%= link_to "delete", admin_book_path(book), method: :delete,
    class: "btn btn-danger", remote: true, data: {confirm: "you sure?"} %>
  </td>
</tr>

app/views/admin/books/_current_fields.html.erb
<div class="fields">
  <p class="col-md-6">
    <%= image_tag f.object.image.url, size: "200x150", class: "img-rounded" %>
    <%= link_to_remove_fields "Remove", f %>
  </p>
</div>

app/views/admin/books/_list_books.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<h1>Listing books</h1>

<% if @books.any? %>

  <%= will_paginate @books %>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Cover</th>
        <th><%= sortable "title" %></th>
        <th><%= sortable "author" %></th>
        <th>Rating</th>
        <th>Action</th>
      </tr>
    </thead>  
    <tbody class="book-index">
      <%= render @books %>
    </tbody>
  </table>

  <%= will_paginate @books %>
  
<% else %>
  <h2 style="center">Empty</h2>
<% end %>

app/views/admin/books/_photo_fields.html.erb
<div class="fields">
  <p class="col-md-6">
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "form-control" %>
    <%= link_to_remove_fields "Remove", f %>
  </p>
</div>

app/views/admin/books/destroy.js.erb
$('#book_<%= @book.id %>').remove();

app/views/admin/books/edit.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
    </section>
  </aside>
  <div class="col-md-8">
    <div class="col-md-12">
      <div class="col-md-8">
        <%= form_for [:admin, @book], html: {multipart: true} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.select :category_id, Category.all.collect{|c| [c.content, c.id]}, include_blank: true %>

          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :author %>
          <%= f.text_field :author, class: 'form-control' %>

          <%= f.label "Number of page" %>
          <%= f.number_field :number_of_pages, in: 1...1000, class: 'form-control' %>

          <%= f.label :publish %>
          <%= f.date_select :publish_date, class: 'form-control' %>

          <%= f.label :Cover %>
          <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>

          <%= f.label "Current Image" %>
          <%= f.fields_for :photos do |builder| %>
            <%= render 'current_fields', f: builder %>
          <% end %>

          <label>New Image</label>
          <p>
            <%= link_to_add_fields "Add Image", f, :photos %>
          </p>
          
          <%= f.submit "Edit Book", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-md-4">
        <label>Current Cover</label>
          <%= image_tag "#{@book.image}", size:"128x128", alt: "Current Cover", class: "img-polaroid" %>
      </div>
    </div>
    <div class="col-md-12">
      <%= link_to "manage books", admin_books_path %>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide(:title, "Manage Books") %>

<div class="row">
  <aside class="col-md-4">
    <div div class="col-md-12">
      <section class="user_info">
        
      </section>
    </div>
  </aside>
  <div class="col-md-8">
    <div div class="col-md-12">
      <%= form_tag admin_books_path, method: 'get', id: "books_search" do %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <div class="col-sm-12 well">
          <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: 'Enter search term...' %>
          </div>
          <div class="col-md-2">
            <%= select_tag("filter", options_for_select([['Title', 'title'], ['Author', 'author']])) %>
          </div>
          <div class="col-md-4">
            <%= select_tag "category_id", options_from_collection_for_select(Category.all, :id, :content), prompt: "Select category" %>
          </div>
        </div>
        <div class="col-md-12">
          <div id="books_div"><%= render 'list_books' %></div>
        </div>
      <% end %>
    </div>
    <div div class="col-md-12">
      <%= link_to "add new book", new_admin_book_path, class: "btn btn-primary"%>
    </div>
  </div>
</div>

app/views/admin/books/index.js.erb
$("#books_div").html("<%= escape_javascript(render('list_books')) %>");

app/views/admin/books/new.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
    </section>
  </aside>
  <div class="col-md-8">
    <div class="col-md-8">
      <%= form_for [:admin, @book], html: {multipart: true} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :category %>
        <%= f.select :category_id, Category.all.collect{|c| [c.content, c.id]}, include_blank: true %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :author %>
        <%= f.text_field :author, class: 'form-control' %>

        <%= f.label "Number of page" %>
        <%= f.number_field :number_of_pages, in: 1...1000, class: 'form-control' %>

        <%= f.label :publish %>
        <%= f.date_select :publish_date, class: 'form-control' %>

        <%= f.label "Cover" %>
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>

        <p>
          <%= link_to_add_fields "Add Image", f, :photos %>
        </p>

        <%= f.submit "Create new book", class: "btn btn-primary" %>
      <% end %>
      <%= link_to "manage books", admin_books_path %>
    </div>
  </div>
</div>