config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  root  'static_pages#home'
  
  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'contact' => 'static_pages#contact'

  resources :users do
    get 'history' => 'book_states#index'
    resources :requests
    resources :favorites
  end

  match '/users/:id/:type', to: 'users#show', via: :get
  resources :relationships, only: [:create, :destroy]

  resources :categories do
    resources :books
  end
  resources :books do
    resources :reviews
    resources :book_states
  end
  resources :reviews do
    resources :comments
  end
  resources :activities do
    resources :likes, only: [:create, :destroy]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :requests
    resources :books
  end

  resources :activities
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
  
  mount_uploader :image, PictureUploader

  validates :content, presence: true, length: {maximum: 150}	
  validate  :image_size

  scope :search_by , ->content {where('content LIKE ?', "%#{content}%")}

  def self.search(search)
    if search
      where('content LIKE ?', "%#{search}%")
    else
      all
    end
  end

  private
  def image_size
    errors.add :image, "should be less than 5MB" if image.size > 5.megabytes
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  respond_to :html, :js

  def index
    @categories = Category.all.search_by(params[:search]).order(sort_column + ' ' + sort_direction)
    @categories = @categories.paginate page: params[:page], per_page: 5
  end

  def new 
    @title = "New Category"
    @category = Category.new
    render 'edit'
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Category created!"
    else
      flash[:danger] = "Create false!"
    end
    redirect_to admin_categories_path
  end

  def edit
    @title = "Edit #{@category.content}"
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "Category updated!"
    else
      flash[:danger] = "Update false!"
    end  
    redirect_to edit_admin_category_path @category
  end

  def destroy
    @category.destroy
  end

  private
  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "content"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit :content, :image
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    #@categories = Category.paginate page: params[:page], per_page: 10
    @categories = Category.search(params[:search]).order(sort_column + " " + sort_direction)
    @categories=@categories.paginate(:per_page => 5, :page => params[:page]) 

    if params[:search]
      @categories = Category.search(params[:search]).order("created_at DESC")
    else
      @categories = Category.all.order('created_at DESC')
    end
  end

  private
  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def category_params
    params.require(:category).permit :content
  end

end

app/views/admin/categories/_category.html.erb
<tr id="category_<%= category.id %>">
  <td>
    <%= image_tag "#{category.image}", size: "32x32", alt: "Category", class: "img-rounded" %>
  </td>
  <td>
    <div class="col-md-12">
      <%= link_to category.content, edit_admin_category_path(category) %>
    </div>
  </td>
  <td>
  <div class="col-md-12">
    <%= link_to "edit", edit_admin_category_path(category), class: "btn btn-success" %>
    <%= link_to "delete", admin_category_path(category), method: :delete,
    class: "btn btn-danger", remote: true, data: {confirm: "you sure?"} %>
  </div>
  </td>
</tr>

app/views/admin/categories/_list_categories.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<h1>Manager Categories</h1>

<% if @categories.any? %>
  <%= will_paginate @categories %>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th><div class="col-md-12"> Image </div></th>
        <th><div class="col-md-12"><%= sortable "content" %></div></th>
        <th><div class="col-md-12"> Action </div></th>
      </tr>
    </thead>  
    <tbody class="category-index">
      <%= render @categories %>
    </tbody>
  </table>

  <%= will_paginate @categories %>
<% else %>
  <h2 style="center">Empty</h2>
<% end %>

app/views/admin/categories/destroy.js.erb
$('#category_<%= @category.id %>').remove();

app/views/admin/categories/edit.html.erb
<% provide :title, @title %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    </section>
    <section>
    </section>
  </aside>
  <div class="col-md-8">
    <h1><%= @title %></h1>
    <div class="col-md-12">
      <%= render 'shared/category_error_messages' %>
      <div class="col-md-2"></div>
      <div class="col-md-6">
        <%= form_for [:admin, @category], html: {multipart: true} do |f| %>
          <div class="col-md-12 well">
            <%= f.label :content %>
            <%= f.text_area :content, placeholder: "Compose new category...", class: 'form-control' %>
          </div>
          <div class="col-md-12 well">
            <%= f.label :image %>
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
          </div>
          <div class="col-md-12 well">
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <% unless params[:id].blank? %>
        <div class="col-md-4 well">
          <label>Current Image</label>
          <%= image_tag "#{@category.image}", alt: "Current Image", class: "img-polaroid" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <div class="col-md-2"></div>
      <div class="col-md-6 well">
        <%= link_to "Manage categories", admin_categories_path, class: "btn btn-primary" %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#category_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/admin/categories/index.html.erb
<% provide :title, "Manager Categories" %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
    </section>
  </aside>
  <div class="col-md-8">
    <div div class="col-md-12">
      <%= form_tag admin_categories_path, method: 'get', id: "categories_search" do %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <div class="col-md-12 well">
          <div class="col-md-3">
            Search
          </div>
          <div class="col-md-6">
            <%= text_field_tag :search, params[:search] %>
          </div>
          <div class="col-md-2">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
          <div class="col-md-1"></div>
        </div>
        <div class="col-md-12">
          <div id="categories_div"><%= render 'list_categories' %></div>
        </div>
      <% end %>
    </div>
    <div div class="col-md-12">
      <%= link_to "add new category", new_admin_category_path, class: "btn btn-primary" %>
      <%= link_to "add new book", new_admin_book_path, class: "btn btn-info"%>
    </div>
  </div>
</div>

app/views/admin/categories/index.js.erb
$("#categories_div").html("<%= j(render "list_categories") %>");