config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  root  'static_pages#home'
  
  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'contact' => 'static_pages#contact'

  resources :users do
    get 'history' => 'book_states#index'
    resources :requests
    resources :favorites
  end

  match '/users/:id/:type', to: 'users#show', via: :get
  resources :relationships, only: [:create, :destroy]

  resources :categories do
    resources :books
  end
  resources :books do
    resources :reviews
    resources :book_states
  end
  resources :reviews do
    resources :comments
  end
  resources :activities do
    resources :likes, only: [:create, :destroy]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :requests
    resources :books
  end

  resources :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :requests, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :book_states, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {maximum: 100}        
  validates :email, presence: true, uniqueness: true, length: {maximum:50}
  validates :role, presence: true, length: {maximum: 50}
  mount_uploader :avatar, PictureUploader

  scope :search_by, ->name {where('name LIKE ?', "%#{name}%")}

  def is_admin?
    role == 'admin'
  end

  def is_user? user
    self == user
  end

  def favorite? book
    !self.favorites.find_by(book: book).nil?
  end

  def like? activity
    !self.likes.find_by(activity: activity).nil?
  end
  
  def follow other_user
    Activity.create user: self, target_id: other_user.id, action_type: "follow"
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    Activity.create user: self, target_id: other_user.id, action_type: "unfollow"
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def to_param
    [id, name.parameterize].join("-")
  end

  def following_ids
    self.following.pluck :id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  helper_method :sort_column, :sort_direction
  respond_to :html, :js

  def index
    @users = User.all.search_by(params[:search]).order(sort_column + ' ' + sort_direction)
    @users = @users.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
  end

  def destroy
    @user = User.find params[:id]
    Activity.destroy_all(target_id: @user.id,
        action_type: ["follow", "unfollow"])
    @user.destroy
  end

  private
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def user_params
    params.require(:user).permit :name, :avatar
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :edit]
  helper_method :sort_column, :sort_direction
  respond_to :html, :js

  def index
    @users = User.all.search_by(params[:search]).order(sort_column + ' ' + sort_direction)
    @users = @users.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
    @activities = Activity.user_activity(current_user).paginate page: params[:page], per_page: 10

    if !params[:type].blank? && ['following', 'followers'].include?(params[:type])
      @title = params[:type]
      @users = @user.send(params[:type])
      @users = @users.paginate page: params[:page]
      render 'show_follow' 
    end

  end   

  def edit
    @user = current_user
  end

  private
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def user_params
    params.require(:user).permit :name, :avatar
  end
end

app/views/admin/users/_list_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<h1>Manager Users</h1>

<% if @users.any? %>
  <%= will_paginate @users %>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th><div class="col-md-12"> Avatar </div></th>
        <th><div class="col-md-12"><%= sortable "name" %></div></th>
        <th><div class="col-md-12"> Action </div></th>
      </tr>
    </thead>  
    <tbody class="user-index">
      <%= render @users %>
    </tbody>
  </table>

  <%= will_paginate @users %>
<% else %>
  <h2 style="center">Empty</h2>
<% end %>

app/views/admin/users/_user.html.erb
<% unless current_user == user %>
  <tr id="user_<%= user.id %>">
    <td>
      <%= image_tag user.avatar, size: "32x32", alt: "User", class: "img-rounded" unless user.avatar.blank? %>
    </td>
    <td>
      <div class="col-md-12">
        <%= link_to user.name, admin_user_path(user) %>
      </div>
    </td>
    <td>
    <div class="col-md-12">
      <%= link_to "delete", admin_user_path(user), method: :delete,
      class: "btn btn-danger", remote: true, data: {confirm: "you sure?"} %>
    </div>
    </td>
  </tr>
<% end %>

app/views/admin/users/destroy.js.erb
$('#user_<%= @user.id %>').remove();

app/views/admin/users/index.html.erb
<% provide :title, "Manager Users" %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
    </section>
  </aside>
  <div class="col-md-8">
    <div div class="col-md-12">
      <%= form_tag admin_users_path, method: 'get', id: "users_search" do %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <div class="col-md-12 well">
          <div class="col-md-6">
            <label>Search form</label>
          </div>
          <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: 'Search user by name...' %>
          </div>
        </div> 
        <div class="col-md-12">
          <div id="users_div"><%= render 'list_users' %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.js.erb
$("#users_div").html("<%= escape_javascript(render("list_users")) %>");

app/views/admin/users/show.html.erb
<% provide :title, @user.name %>
<h2><%= @user.name %></h2>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
    </section>
  </aside>
  <div class="col-md-8">
    <div class="col-md-12">
      <div class="col-md-4">
        <%= image_tag "#{@user.avatar}", id: "book-image", alt: "Book" %>
      </div>
      <div class="col-md-8">
        <div class="col-md-12">User : <%= @user.name %></div>
      </div>
    </div>
    <div class="col-md-12">
      <h1>Activities</h1>
      
    </div>
  </div>
</div> 